"""Creacion inicial de tablas

Revision ID: 4e4217d0c9be
Revises: 
Create Date: 2026-02-25 00:24:41.687865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e4217d0c9be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('passwd_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('amistades',
    sa.Column('user_1', sa.String(length=50), nullable=False),
    sa.Column('user_2', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADA', 'RECHAZADA', name='estado_amistad_enum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['user_1'], ['usuarios.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2'], ['usuarios.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_1', 'user_2')
    )
    op.create_table('estadisticas',
    sa.Column('nombre_user', sa.String(length=50), nullable=False),
    sa.Column('num_partidas_jugadas', sa.Integer(), nullable=False),
    sa.Column('num_partidas_ganadas', sa.Integer(), nullable=False),
    sa.Column('num_continentes_conquistados', sa.Integer(), nullable=False),
    sa.Column('num_soldados_matados', sa.Integer(), nullable=False),
    sa.CheckConstraint('num_continentes_conquistados >= 0', name='check_regiones_positivas'),
    sa.CheckConstraint('num_partidas_ganadas >= 0', name='check_partidas_ganadas_positivas'),
    sa.CheckConstraint('num_partidas_jugadas >= 0', name='check_partidas_jugadas_positivas'),
    sa.CheckConstraint('num_soldados_matados >= 0', name='check_tropas_positivas'),
    sa.ForeignKeyConstraint(['nombre_user'], ['usuarios.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nombre_user')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_max_players', sa.Integer(), nullable=False),
    sa.Column('config_visibility', sa.Enum('PUBLICA', 'PRIVADA', name='tipo_visibilidad_enum', create_constraint=True), nullable=False),
    sa.Column('codigo_invitacion', sa.String(length=10), nullable=False),
    sa.Column('config_timer_seconds', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('CREANDO', 'ACTIVA', 'PAUSADA', 'FINALIZADA', name='estado_partida_enum', create_constraint=True), nullable=False),
    sa.Column('ganador', sa.String(length=50), nullable=True),
    sa.CheckConstraint('config_max_players >= 2 AND config_max_players <= 4', name='check_max_players_valido'),
    sa.CheckConstraint('config_timer_seconds > 0', name='check_timer_valido'),
    sa.ForeignKeyConstraint(['ganador'], ['usuarios.username'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_codigo_invitacion'), 'partidas', ['codigo_invitacion'], unique=True)
    op.create_table('estado_partida',
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('fase_actual', sa.Enum('REFUERZO', 'GESTION', 'ATAQUE_CONVENCIONAL', 'ATAQUE_ESPECIAL', 'FORTIFICACION', name='fase_partida_enum', create_constraint=True), nullable=False),
    sa.Column('fin_fase_actual', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_turno_actual', sa.String(length=50), nullable=False),
    sa.Column('mapa', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jugadores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_turno_actual'], ['usuarios.username'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('partida_id')
    )
    op.create_table('jugadores_partida',
    sa.Column('usuario_id', sa.String(length=50), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.Column('estado_jugador', sa.Enum('VIVO', 'MUERTO', name='estado_jugador_enum', create_constraint=True), nullable=False),
    sa.Column('color', sa.Enum('ROJO', 'AZUL', 'VERDE', 'AMARILLO', name='color_jugador_enum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'partida_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jugadores_partida')
    op.drop_table('estado_partida')
    op.drop_index(op.f('ix_partidas_codigo_invitacion'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_table('estadisticas')
    op.drop_table('amistades')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
