"""add creador a partida

Revision ID: 6e5f12242cd2
Revises: 4e4217d0c9be
Create Date: 2026-03-28 03:25:12.311398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e5f12242cd2'
down_revision: Union[str, Sequence[str], None] = '4e4217d0c9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadores_partida', 'color')
    op.add_column('partidas', sa.Column('creador', sa.String(length=50), nullable=True))
    op.execute("UPDATE partidas SET creador = 'roldan' WHERE creador IS NULL")
    op.alter_column('partidas', 'creador', nullable=False)
    op.create_foreign_key(None, 'partidas', 'usuarios', ['creador'], ['username'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidas', type_='foreignkey')
    op.drop_column('partidas', 'creador')
    op.add_column('jugadores_partida', sa.Column('color', postgresql.ENUM('ROJO', 'AZUL', 'VERDE', 'AMARILLO', name='color_jugador_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
