"""add_logs_partida

Revision ID: f37f12c57e10
Revises: f511144f48e9
Create Date: 2026-04-26 11:53:25.710574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37f12c57e10'
down_revision: Union[str, Sequence[str], None] = 'f511144f48e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_partida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('turno_numero', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_partida_partida_id'), 'logs_partida', ['partida_id'], unique=False)
    op.add_column('estado_partida', sa.Column('turno_actual', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('usuarios', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'avatar')
    op.drop_column('estado_partida', 'turno_actual')
    op.drop_index(op.f('ix_logs_partida_partida_id'), table_name='logs_partida')
    op.drop_table('logs_partida')
    # ### end Alembic commands ###
